name: simon_pkl
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  badges: ^3.1.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  iconify: 0.0.1
  iconify_flutter: ^0.0.5
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  string_capitalize: ^0.0.10


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: launcher_icon
  image_path: assets/logo/simon-logo.png
  ios: true

flutter:
  assets:
    - assets/logo/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 800
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Medium.ttf
          weight: 400
  uses-material-design: true
