name: simon_pkl
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  badges: ^3.1.2
  calendar_date_picker2: ^1.0.2
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.10.7
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  iconify: 0.0.1
  flutter_local_notifications: ^17.1.2
  iconify_flutter: ^0.0.5
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  string_capitalize: ^0.0.10
  android_notification_icons: ^0.0.1
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  skeletonizer: ^1.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

android_notification_icons:
  image_path: assets/logo/logo-simon-var2.png

flutter_launcher_icons:
  android: launcher_icon
  image_path: assets/logo/simon-logo.png
  ios: true

flutter:
  assets:
    - assets/logo/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 800
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Medium.ttf
          weight: 400
  uses-material-design: true
